# Google Cloud Build configuration
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/imdb-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/imdb-backend:latest',
      '-f', 'Dockerfile',
      '.'
    ]

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/imdb-frontend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/imdb-frontend:latest',
      '-f', 'frontend/Dockerfile',
      './frontend'
    ]

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/imdb-backend:latest']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/imdb-frontend:latest']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'imdb-backend',
      '--image', 'gcr.io/$PROJECT_ID/imdb-backend:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'PORT=3000',
      '--set-secrets', 'MONGODB_URI=mongodb-uri:latest',
      '--set-secrets', 'JWT_SECRET=jwt-secret:latest',
      '--set-secrets', 'REDIS_URL=redis-url:latest'
    ]

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'imdb-frontend',
      '--image', 'gcr.io/$PROJECT_ID/imdb-frontend:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '80',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10'
    ]

images:
  - 'gcr.io/$PROJECT_ID/imdb-backend:latest'
  - 'gcr.io/$PROJECT_ID/imdb-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

timeout: '1200s'
